/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import OperationsAndServices.FlightDataLists;
import OperationsAndServices.ReservationOperations;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reservationObjects.Admin;
import reservationObjects.Airport;
import reservationObjects.Customer;
import reservationObjects.Flight;
import reservationObjects.Reservation;

/**
 *
 * @author Zahera
 */
public class AdminManagementPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminManagementPage
     */
    DefaultListModel dlm1;
    DefaultListModel dlm2;
    MainFrame mainFrame;
    FlightDataLists flightDataLists;
    Admin loggedinAdmin;
    DefaultTableModel dtm;
    Vector<String> flightTableColumnsNames;
    Vector<Flight> flights;

    Vector<Airport> airports;
    Vector<Customer> customers;
    ReservationOperations reservationOperations;

    public AdminManagementPage(MainFrame mainFrame, FlightDataLists flightDataLists, Admin loggedinAdmin) {
        this.mainFrame = mainFrame;
        this.flightDataLists = flightDataLists;
        this.loggedinAdmin = loggedinAdmin;
        this.flights = flightDataLists.getFlights();
        this.customers = flightDataLists.getCustomers();

        this.airports = flightDataLists.getAirports();
        initComponents();

        lbl_username.setText(loggedinAdmin.getFirstName() + " password:  " + loggedinAdmin.getPassword());
        flightTableColumnsNames = initializeFlightTableColumnsNames();
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(flightTableColumnsNames);
        flightsTable.setModel(dtm);

        reservationOperations = new ReservationOperations(flightDataLists);

        setValuesForComboBoxes();
             
        dlm1= new DefaultListModel();
        dlm2= new DefaultListModel();
        reservationList.setModel(dlm1);
        emailsList.setModel(dlm2);
        
        setListData();
    }
    public void setListData(){
        for(Reservation reservation : flightDataLists.getReservations()){
            dlm1.addElement("flight ID: " + reservation.getFlight().getFlightId()+ "___ count: "+ reservation.getReservedSeats().size());
        }
        for(Customer customer: flightDataLists.getCustomers()){
            dlm2.addElement(customer.getEmail());
        }
    }
    public Vector<String> initializeFlightTableColumnsNames() {
        Vector<String> names = new Vector<>();
        names.add("flight Id");
        names.add("departure");
        names.add("arrival");
        names.add("departure date");
        names.add("seat count");
        names.add("seat price");
        names.add("available seats");
        return names;
    }

    public void setValuesForComboBoxes() {
        int size = airports.size();
        for (int i = 0; i < size; i++) {
            combo_origin.addItem(airports.elementAt(i).getCity());
            combo_destination.addItem(airports.elementAt(size - i - 1).getCity());
        }
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_adminManagementPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        btn_addFlight = new javax.swing.JButton();
        txt_seatNumber = new javax.swing.JTextField();
        txt_seatPrice = new javax.swing.JTextField();
        btn_editSelectedFlight = new javax.swing.JButton();
        btn_removeSelevtedFlight = new javax.swing.JButton();
        btn_showAllFlights = new javax.swing.JButton();
        combo_origin = new javax.swing.JComboBox<>();
        combo_destination = new javax.swing.JComboBox<>();
        txt_dateTime = new javax.swing.JTextField();
        btn_logoutAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reservationList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        emailsList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        lbl_adminManagementPage.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lbl_adminManagementPage.setForeground(new java.awt.Color(0, 102, 102));
        lbl_adminManagementPage.setText("Admin Management Page");

        flightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", ""
            }
        ));
        jScrollPane1.setViewportView(flightsTable);

        jLabel1.setText("username : ");

        lbl_username.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(102, 0, 102));
        lbl_username.setText("jLabel2");

        btn_addFlight.setBackground(new java.awt.Color(255, 153, 255));
        btn_addFlight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addFlight.setText("add Flight");
        btn_addFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addFlightActionPerformed(evt);
            }
        });

        txt_seatNumber.setText("enter seat number");
        txt_seatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatNumberActionPerformed(evt);
            }
        });

        txt_seatPrice.setText("enter seat price");
        txt_seatPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatPriceActionPerformed(evt);
            }
        });

        btn_editSelectedFlight.setBackground(new java.awt.Color(255, 102, 255));
        btn_editSelectedFlight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_editSelectedFlight.setText("edit flight ");
        btn_editSelectedFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editSelectedFlightActionPerformed(evt);
            }
        });

        btn_removeSelevtedFlight.setBackground(new java.awt.Color(255, 153, 255));
        btn_removeSelevtedFlight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_removeSelevtedFlight.setText("remove flight");
        btn_removeSelevtedFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeSelevtedFlightActionPerformed(evt);
            }
        });

        btn_showAllFlights.setBackground(new java.awt.Color(255, 102, 255));
        btn_showAllFlights.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_showAllFlights.setText("show all flights");
        btn_showAllFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showAllFlightsActionPerformed(evt);
            }
        });

        txt_dateTime.setText("dd-MM-yyyy HH:mm");

        btn_logoutAdmin.setBackground(new java.awt.Color(102, 255, 204));
        btn_logoutAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logoutAdmin.setText("LOGOUT");
        btn_logoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutAdminActionPerformed(evt);
            }
        });

        jLabel3.setText("**  to remove or edit a flight, you have to select a flight on the table");

        jScrollPane2.setViewportView(reservationList);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("view reservation history");

        jScrollPane3.setViewportView(emailsList);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("registered customers emails list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(combo_origin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_seatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(btn_editSelectedFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_removeSelevtedFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(btn_showAllFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_logoutAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lbl_adminManagementPage)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(lbl_username))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_adminManagementPage)
                    .addComponent(jLabel1)
                    .addComponent(lbl_username))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_seatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addFlight)
                    .addComponent(btn_editSelectedFlight)
                    .addComponent(btn_removeSelevtedFlight)
                    .addComponent(btn_showAllFlights))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logoutAdmin)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showAllFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showAllFlightsActionPerformed
        // TODO add your handling code here: 
        dtm.setRowCount(0);
        for (int i = 0; i < flights.size(); i++) {
            Flight flight = flights.elementAt(i);
            dtm.addRow(prepareFlightRow(flight));
        }
    }//GEN-LAST:event_btn_showAllFlightsActionPerformed

    private void btn_addFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addFlightActionPerformed
        // TODO add your handling code here:
        Airport originAirport = reservationOperations.returnAirportByCity(combo_origin.getSelectedItem().toString());
        Airport destinationAirport = reservationOperations.returnAirportByCity(combo_destination.getSelectedItem().toString());
        LocalDateTime dateTime;
        
        if(combo_origin.getSelectedItem().toString().equals(combo_destination.getSelectedItem().toString())){
            throw new IllegalArgumentException();
        }

        try {
            String txtDateTime = txt_dateTime.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            int seatNumber = Integer.parseInt(txt_seatNumber.getText());
            int seatPrice = Integer.parseInt(txt_seatPrice.getText());
            dateTime = LocalDateTime.parse(txtDateTime, formatter);
            Flight flight = new Flight(originAirport, destinationAirport, dateTime, seatNumber, seatPrice);
            reservationOperations.addFlightToList(flight);
            dtm.addRow(prepareFlightRow(flight));
            JOptionPane.showMessageDialog(mainFrame, "FLIGHT ADDED SUCCESSFULLY ");

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(mainFrame, "Invalid date-time format. Please use dd-MM-yyyy HH:mm");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(mainFrame, "invalid format for numbers,\n check the number does not include any spaces or special characters");
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(mainFrame, "a flight cannot has the same origin and destiantion");
        }

    }//GEN-LAST:event_btn_addFlightActionPerformed

    private void txt_seatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatNumberActionPerformed

    private void txt_seatPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatPriceActionPerformed

    private void btn_editSelectedFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editSelectedFlightActionPerformed
        // TODO add your handling code here:
        
        if(flightsTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(mainFrame, "please select a flight to continue");
            return;
        }
        int flightId=Integer.parseInt(dtm.getValueAt(flightsTable.getSelectedRow(), 0).toString());
        Flight flight = reservationOperations.getFlightById(flightId);
        if(flight.getReservations().size()>0){
            JOptionPane.showMessageDialog(mainFrame, "flight cannot be edited or deleted because it has already reserved by some customers");
            return;
        }
        Airport originAirport = reservationOperations.returnAirportByCity(combo_origin.getSelectedItem().toString());
        Airport destinationAirport = reservationOperations.returnAirportByCity(combo_destination.getSelectedItem().toString());
        LocalDateTime dateTime;

        try {
            String txtDateTime = txt_dateTime.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            int seatNumber = Integer.parseInt(txt_seatNumber.getText());
            int seatPrice = Integer.parseInt(txt_seatPrice.getText());
            dateTime = LocalDateTime.parse(txtDateTime, formatter);

            
            flight.setOriginAirport(originAirport);
            flight.setDestinationAirport(destinationAirport);
            flight.setDepartureTime(dateTime);
            flight.setFlightSeatNumber(seatNumber);
            flight.setSeatPrice(seatPrice);
            
            btn_showAllFlightsActionPerformed(evt);

            JOptionPane.showMessageDialog(mainFrame, "FLIGHT EDITED SUCCESSFULLY ");

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(mainFrame, "Invalid date-time format. Please use dd-MM-yyyy HH:mm");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(mainFrame, "invalid format for numbers,\n check the number does not include any spaces or special characters");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(mainFrame, "flight not found");
        } 
    }//GEN-LAST:event_btn_editSelectedFlightActionPerformed

    private void btn_logoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutAdminActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanelMethod("LoginPage");
        loggedinAdmin.setLoggedIn(false);
    }//GEN-LAST:event_btn_logoutAdminActionPerformed

    private void btn_removeSelevtedFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeSelevtedFlightActionPerformed
        // TODO add your handling code here:  
        if(flightsTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(mainFrame, "please select a flight to continue");
            return;
        }
        int flightId=Integer.parseInt(dtm.getValueAt(flightsTable.getSelectedRow(), 0).toString());
        
        Flight flight = reservationOperations.getFlightById(flightId);
        if(!flight.getReservations().isEmpty()){
            JOptionPane.showMessageDialog(mainFrame, "flight cannot be edited or deleted because it has already reserved by some customers");
            return;
        }
        boolean found = false;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            int idOnTable = Integer.parseInt(dtm.getValueAt(i, 0).toString());
            if (idOnTable == flightId) {
                dtm.removeRow(i);
                flightDataLists.getFlights().remove(flight);
                found = true;
                break;
            }
        }

        if (found) {
            btn_showAllFlightsActionPerformed(evt); // refresh the table
            
            JOptionPane.showMessageDialog(mainFrame, "Flight deleted successfully");
            //delete assosiated reservations
            for(Reservation reservation: flightDataLists.getReservations()){
                if(reservation.getFlight().getFlightId()==flightId){
                    flightDataLists.getReservations().remove(reservation);
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(mainFrame, "Flight not found!");
        }
    }//GEN-LAST:event_btn_removeSelevtedFlightActionPerformed
    public Vector<String> prepareFlightRow(Flight flight) {
        Vector<String> row = new Vector<>();
        String id = String.valueOf(flight.getFlightId());
        String arrival = flight.getOriginAirport().getCity();
        String destination = flight.getDestinationAirport().getCity();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
        String formattedDate = flight.getDepartureTime().format(formatter);
        String seatNumber = String.valueOf(flight.getFlightSeatNumber());
        String seatPrice = String.valueOf(flight.getSeatPrice());
        String remainedSeats= String.valueOf(flight.getAvalilableSeats().size());
        row.add(id);
        row.add(arrival);
        row.add(destination);
        row.add(formattedDate);
        row.add(seatNumber);
        row.add(seatPrice);
        row.add(remainedSeats);
        return row;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addFlight;
    private javax.swing.JButton btn_editSelectedFlight;
    private javax.swing.JButton btn_logoutAdmin;
    private javax.swing.JButton btn_removeSelevtedFlight;
    private javax.swing.JButton btn_showAllFlights;
    private javax.swing.JComboBox<String> combo_destination;
    private javax.swing.JComboBox<String> combo_origin;
    private javax.swing.JList<String> emailsList;
    private javax.swing.JTable flightsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_adminManagementPage;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JList<String> reservationList;
    private javax.swing.JTextField txt_dateTime;
    private javax.swing.JTextField txt_seatNumber;
    private javax.swing.JTextField txt_seatPrice;
    // End of variables declaration//GEN-END:variables
}
