/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import OperationsAndServices.FlightDataLists;
import OperationsAndServices.ReservationOperations;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reservationObjects.Admin;
import reservationObjects.Airport;
import reservationObjects.Customer;
import reservationObjects.Flight;

/**
 *
 * @author Zahera
 */
public class AdminManagementPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminManagementPage
     */
    DefaultListModel dlm1;
    DefaultListModel dlm2;
    MainFrame mainFrame;
    FlightDataLists flightDataLists;
    Admin loggedinAdmin;
    DefaultTableModel dtm;
    Vector<String> flightTableColumnsNames;
    Vector<Flight> flights;

    Vector<Airport> airports;
    Vector<Customer> customers;
    ReservationOperations reservationOperations;

    public AdminManagementPage(MainFrame mainFrame, FlightDataLists flightDataLists, Admin loggedinAdmin) {
        this.mainFrame = mainFrame;
        this.flightDataLists = flightDataLists;
        this.loggedinAdmin = loggedinAdmin;
        this.flights = flightDataLists.getFlights();
        this.customers = flightDataLists.getCustomers();

        this.airports = flightDataLists.getAirports();
        initComponents();

        lbl_username.setText(loggedinAdmin.getFirstName() + " " + loggedinAdmin.getLastName());
        flightTableColumnsNames = initializeFlightTableColumnsNames();
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(flightTableColumnsNames);
        flightsTable.setModel(dtm);

        reservationOperations = new ReservationOperations(flightDataLists);

        setValuesForComboBoxes();
        
        initializeFlightIDcombobox();
        
        dlm1= new DefaultListModel();
        dlm2= new DefaultListModel();
        list_customers.setModel(dlm1);
        list_airports.setModel(dlm2);;
        
        setListData();
    }
    public void setListData(){
        for(Customer customer: flightDataLists.getCustomers()){
            dlm1.addElement(customer.getEmail());
        }
        for(Airport airport: flightDataLists.getAirports()){
            dlm2.addElement(airport.getAirportName());
        }
    }
    public Vector<String> initializeFlightTableColumnsNames() {
        Vector<String> names = new Vector<>();
        names.add("flight Id");
        names.add("departure");
        names.add("arrival");
        names.add("departure date");
        names.add("seat number");
        names.add("seat price");
        return names;
    }

    public void setValuesForComboBoxes() {
        int size = airports.size();
        for (int i = 0; i < size; i++) {
            combo_origin.addItem(airports.elementAt(i).getCity());
            combo_destination.addItem(airports.elementAt(size - i - 1).getCity());
        }
    }

    public void initializeFlightIDcombobox() {
        combo_flightID.removeAllItems();
        for (Flight flight : flights) {
            combo_flightID.addItem(String.valueOf(flight.getFlightId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_adminManagementPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        btn_addFlight = new javax.swing.JButton();
        txt_seatNumber = new javax.swing.JTextField();
        txt_seatPrice = new javax.swing.JTextField();
        btn_editSelectedFlight = new javax.swing.JButton();
        btn_removeSelevtedFlight = new javax.swing.JButton();
        btn_showAllFlights = new javax.swing.JButton();
        combo_origin = new javax.swing.JComboBox<>();
        combo_destination = new javax.swing.JComboBox<>();
        txt_dateTime = new javax.swing.JTextField();
        combo_flightID = new javax.swing.JComboBox<>();
        btn_logoutAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_customers = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_airports = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lbl_adminManagementPage.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lbl_adminManagementPage.setForeground(new java.awt.Color(0, 153, 153));
        lbl_adminManagementPage.setText("Admin Management Page");

        flightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(flightsTable);

        jLabel1.setText("username : ");

        lbl_username.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(102, 0, 102));
        lbl_username.setText("jLabel2");

        btn_addFlight.setText("add Flight");
        btn_addFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addFlightActionPerformed(evt);
            }
        });

        txt_seatNumber.setText("enter seat number");
        txt_seatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatNumberActionPerformed(evt);
            }
        });

        txt_seatPrice.setText("enter seat price");
        txt_seatPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatPriceActionPerformed(evt);
            }
        });

        btn_editSelectedFlight.setText("edit flight by id ");
        btn_editSelectedFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editSelectedFlightActionPerformed(evt);
            }
        });

        btn_removeSelevtedFlight.setText("remove flight by id");
        btn_removeSelevtedFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeSelevtedFlightActionPerformed(evt);
            }
        });

        btn_showAllFlights.setText("show all flights");
        btn_showAllFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showAllFlightsActionPerformed(evt);
            }
        });

        txt_dateTime.setText("dd-MM-yyyy HH:mm");

        btn_logoutAdmin.setText("LOGOUT");
        btn_logoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutAdminActionPerformed(evt);
            }
        });

        jLabel3.setText("**  to remove or edit a flight, you have only to  choose id from ID comboBox and click on the button");

        jScrollPane2.setViewportView(list_customers);

        jScrollPane3.setViewportView(list_airports);

        jLabel2.setText("view customer emails");

        jLabel4.setText("view airports names");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl_adminManagementPage)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(lbl_username))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(combo_flightID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(combo_origin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(combo_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_seatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_editSelectedFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_removeSelevtedFlight)
                                .addGap(39, 39, 39)
                                .addComponent(btn_showAllFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(btn_logoutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_adminManagementPage)
                    .addComponent(jLabel1)
                    .addComponent(lbl_username))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_seatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_seatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_flightID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addFlight)
                    .addComponent(btn_editSelectedFlight)
                    .addComponent(btn_removeSelevtedFlight)
                    .addComponent(btn_showAllFlights))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btn_logoutAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showAllFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showAllFlightsActionPerformed
        // TODO add your handling code here: 
        dtm.setRowCount(0);
        for (int i = 0; i < flights.size(); i++) {
            Flight flight = flights.elementAt(i);
            dtm.addRow(prepareFlightRow(flight));
        }
    }//GEN-LAST:event_btn_showAllFlightsActionPerformed

    private void btn_addFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addFlightActionPerformed
        // TODO add your handling code here:
        Airport originAirport = reservationOperations.returnAirportByCity(combo_origin.getSelectedItem().toString());
        Airport destinationAirport = reservationOperations.returnAirportByCity(combo_destination.getSelectedItem().toString());
        LocalDateTime dateTime;

        try {
            String txtDateTime = txt_dateTime.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            int seatNumber = Integer.parseInt(txt_seatNumber.getText());
            int seatPrice = Integer.parseInt(txt_seatPrice.getText());
            dateTime = LocalDateTime.parse(txtDateTime, formatter);
            Flight flight = new Flight(originAirport, destinationAirport, dateTime, seatNumber, seatPrice);
            reservationOperations.addFlightToList(flight);
            dtm.addRow(prepareFlightRow(flight));
            initializeFlightIDcombobox();
            JOptionPane.showMessageDialog(mainFrame, "FLIGHT ADDED SUCCESSFULLY ");

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(mainFrame, "Invalid date-time format. Please use dd-MM-yyyy HH:mm");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(mainFrame, "invalid format for numbers,\n check the number does not include any spaces or special characters");
        }

    }//GEN-LAST:event_btn_addFlightActionPerformed

    private void txt_seatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatNumberActionPerformed

    private void txt_seatPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatPriceActionPerformed

    private void btn_editSelectedFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editSelectedFlightActionPerformed
        // TODO add your handling code here:
        Flight flight = reservationOperations.getFlightById(Integer.parseInt(combo_flightID.getSelectedItem().toString()));
        Airport originAirport = reservationOperations.returnAirportByCity(combo_origin.getSelectedItem().toString());
        Airport destinationAirport = reservationOperations.returnAirportByCity(combo_destination.getSelectedItem().toString());
        LocalDateTime dateTime;

        try {
            String txtDateTime = txt_dateTime.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            int seatNumber = Integer.parseInt(txt_seatNumber.getText());
            int seatPrice = Integer.parseInt(txt_seatPrice.getText());
            dateTime = LocalDateTime.parse(txtDateTime, formatter);

            
            flight.setOriginAirport(originAirport);
            flight.setDestinationAirport(destinationAirport);
            flight.setDepartureTime(dateTime);
            flight.setFlightSeatNumber(seatNumber);
            flight.setSeatPrice(seatPrice);
            
            btn_showAllFlightsActionPerformed(evt);

            JOptionPane.showMessageDialog(mainFrame, "FLIGHT EDITED SUCCESSFULLY ");

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(mainFrame, "Invalid date-time format. Please use dd-MM-yyyy HH:mm");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(mainFrame, "invalid format for numbers,\n check the number does not include any spaces or special characters");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(mainFrame, "flight not found");
        } 
    }//GEN-LAST:event_btn_editSelectedFlightActionPerformed

    private void btn_logoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutAdminActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanelMethod("LoginPage");
        loggedinAdmin.setLoggedIn(false);
    }//GEN-LAST:event_btn_logoutAdminActionPerformed

    private void btn_removeSelevtedFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeSelevtedFlightActionPerformed
        // TODO add your handling code here:  
        int flightId = Integer.parseInt(combo_flightID.getSelectedItem().toString());
        Flight flight = reservationOperations.getFlightById(flightId);

        boolean found = false;

        for (int i = 0; i < dtm.getRowCount(); i++) {
            int idOnTable = Integer.parseInt(dtm.getValueAt(i, 0).toString());
            if (idOnTable == flightId) {
                dtm.removeRow(i);
                flightDataLists.getFlights().remove(flight);
                found = true;
                break;
            }
        }

        if (found) {
            btn_showAllFlightsActionPerformed(evt); // refresh the table
            combo_flightID.removeItem(String.valueOf(flightId)); // remove from combo box
            JOptionPane.showMessageDialog(mainFrame, "Flight deleted successfully");
        } else {
            JOptionPane.showMessageDialog(mainFrame, "Flight not found!");
        }
    }//GEN-LAST:event_btn_removeSelevtedFlightActionPerformed
    public Vector<String> prepareFlightRow(Flight flight) {
        Vector<String> row = new Vector<>();
        String id = String.valueOf(flight.getFlightId());
        String arrival = flight.getOriginAirport().getCity();
        String destination = flight.getDestinationAirport().getCity();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
        String formattedDate = flight.getDepartureTime().format(formatter);
        String seatNumber = String.valueOf(flight.getFlightSeatNumber());
        String seatPrice = String.valueOf(flight.getSeatPrice());
        row.add(id);
        row.add(arrival);
        row.add(destination);
        row.add(formattedDate);
        row.add(seatNumber);
        row.add(seatPrice);
        return row;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addFlight;
    private javax.swing.JButton btn_editSelectedFlight;
    private javax.swing.JButton btn_logoutAdmin;
    private javax.swing.JButton btn_removeSelevtedFlight;
    private javax.swing.JButton btn_showAllFlights;
    private javax.swing.JComboBox<String> combo_destination;
    private javax.swing.JComboBox<String> combo_flightID;
    private javax.swing.JComboBox<String> combo_origin;
    private javax.swing.JTable flightsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_adminManagementPage;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JList<String> list_airports;
    private javax.swing.JList<String> list_customers;
    private javax.swing.JTextField txt_dateTime;
    private javax.swing.JTextField txt_seatNumber;
    private javax.swing.JTextField txt_seatPrice;
    // End of variables declaration//GEN-END:variables
}
