/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import OperationsAndServices.FlightDataLists;
import OperationsAndServices.ReservationOperations;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import reservationObjects.Airport;
import reservationObjects.Customer;
import reservationObjects.Flight;
import reservationObjects.Reservation;

/**
 *
 * @author Zahera
 */
public class CustomerHistory extends javax.swing.JPanel {

    MainFrame mainFrame;
    FlightDataLists flightDataLists;
    DefaultTableModel dtm;

    Customer LoggedinCustomer;
    ReservationOperations reservationOperations;
    Vector<Flight> flights;
    Vector<Airport> airports;

    public CustomerHistory(MainFrame mainFrame, FlightDataLists flightDataLists, Customer loggedinCustomer) {
        this.mainFrame = mainFrame;
        this.flightDataLists = flightDataLists;
        this.LoggedinCustomer = loggedinCustomer;
        this.flights = flightDataLists.getFlights();
        this.airports = flightDataLists.getAirports();
        reservationOperations = new ReservationOperations(flightDataLists);
        initComponents();
        lbl_username.setText(loggedinCustomer.getFirstName() + " password: " + loggedinCustomer.getPassword());

        dtm = new DefaultTableModel();

        reservationTable.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"Reservation ID", "Origin", "Destination", "Departure at", "Seats", "Price"});

        setTableValues();

    }

    public Vector<String> prepareReservationRow(Reservation reservation) {
        Vector<String> row = new Vector<>();
        String reservationID = String.valueOf(reservation.getReservationId());
        String origin = reservation.getFlight().getOriginAirport().getCity();
        String destination = reservation.getFlight().getDestinationAirport().getCity();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
        String formattedDate = reservation.getFlight().getDepartureTime().format(formatter);
        String reservedSeats = String.valueOf(reservation.getReservedSeats().size());
        String price = String.valueOf(reservation.getTicketPrice());
        row.add(reservationID);
        row.add(origin);
        row.add(destination);
        row.add(formattedDate);
        row.add(reservedSeats);
        row.add(price);
        return row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        lbl_username = new javax.swing.JLabel();
        btn_showBoardingPass = new javax.swing.JButton();
        btn_goToCustomerPage = new javax.swing.JButton();
        cancelReservation = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Customer History");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Last Reservations");

        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "reservation ID", "origin ", "destination ", "departure time", "reserved seat count ", "reservation price"
            }
        ));
        jScrollPane1.setViewportView(reservationTable);

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(153, 0, 153));
        lbl_username.setText("username");

        btn_showBoardingPass.setBackground(new java.awt.Color(255, 153, 204));
        btn_showBoardingPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_showBoardingPass.setText("show boarding pass for selected reservation");
        btn_showBoardingPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showBoardingPassActionPerformed(evt);
            }
        });

        btn_goToCustomerPage.setBackground(new java.awt.Color(153, 255, 204));
        btn_goToCustomerPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_goToCustomerPage.setText("return to customer page");
        btn_goToCustomerPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goToCustomerPageActionPerformed(evt);
            }
        });

        cancelReservation.setBackground(new java.awt.Color(255, 153, 204));
        cancelReservation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelReservation.setText("cancel selected reservation");
        cancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText(" username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btn_showBoardingPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btn_goToCustomerPage)
                            .addGap(200, 200, 200)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(97, 97, 97)
                            .addComponent(jLabel3)
                            .addGap(104, 104, 104)
                            .addComponent(lbl_username)
                            .addGap(191, 191, 191))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(619, 619, 619))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(lbl_username))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_showBoardingPass)
                    .addComponent(cancelReservation))
                .addGap(18, 18, 18)
                .addComponent(btn_goToCustomerPage)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
     public void setTableValues() {
        for (Reservation reservation : LoggedinCustomer.getCustomerReservations()) {
            dtm.addRow(prepareReservationRow(reservation));
        }
    }
    private void btn_showBoardingPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showBoardingPassActionPerformed
        // TODO add your handling code here:
        if (reservationTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(mainFrame, "please select a flight to continue");
            return;
        }
        int reservationId = Integer.parseInt(dtm.getValueAt(reservationTable.getSelectedRow(), 0).toString());
        Reservation reservation = reservationOperations.getReservationByID(reservationId);
        BoardingPass boardingPass = new BoardingPass(mainFrame, reservation);
        mainFrame.mainPanel.add(boardingPass, "boardingPass");
        mainFrame.showPanelMethod("boardingPass");

    }//GEN-LAST:event_btn_showBoardingPassActionPerformed

    private void btn_goToCustomerPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goToCustomerPageActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanelMethod("CustomerReservationPage");
    }//GEN-LAST:event_btn_goToCustomerPageActionPerformed

    private void cancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationActionPerformed
        // TODO add your handling code here:
        if (reservationTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(mainFrame, "please select a flight to continue");
            return;
        }
        int reservationId = Integer.parseInt(dtm.getValueAt(reservationTable.getSelectedRow(), 0).toString());
        Reservation reservation = reservationOperations.getReservationByID(reservationId);
        if (reservation == null) {
            JOptionPane.showMessageDialog(mainFrame, "reservation not found");
            return;
        }
        LoggedinCustomer.getCustomerReservations().remove(reservation);
        reservationOperations.deleteReservationFromList(reservation);
        Flight flight = reservation.getFlight();
        flight.getReservations().remove(reservation);
        flight.unReserveSeats(reservation.getReservedSeats());

        JOptionPane.showMessageDialog(mainFrame, "Reservation canceled successfully.");

        // Refresh table
        dtm.setRowCount(0);
        setTableValues();
    }//GEN-LAST:event_cancelReservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goToCustomerPage;
    private javax.swing.JButton btn_showBoardingPass;
    private javax.swing.JButton cancelReservation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTable reservationTable;
    // End of variables declaration//GEN-END:variables
}
