/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import OperationsAndServices.FlightDataLists;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.util.Vector;
import javax.swing.JPanel;
import reservationObjects.Admin;
import reservationObjects.Airport;
import reservationObjects.Customer;
import reservationObjects.Flight;

/**
 *
 * @author Zahera
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    CardLayout cardLayout;
    JPanel mainPanel;
    
    Vector<Flight> flights;
    Vector<Airport> airports;
    
    static FlightDataLists flightDataLists = new FlightDataLists();
    
    public MainFrame() {
        initComponents();
        initializeValues();
        
        cardLayout= new CardLayout();
        mainPanel= new JPanel(cardLayout);
        RegisterPage registerPage= new RegisterPage(this,flightDataLists);
        LoginPage loginPage= new LoginPage(this,flightDataLists);
        
        mainPanel.add(registerPage,"RegisterPage");
        mainPanel.add(loginPage,"LoginPage");
        
        setContentPane(mainPanel);
        setSize(850, 750);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        setVisible(true);
        
        
        this.flights= flightDataLists.getFlights();
        this.airports= flightDataLists.getAirports();
        
        initializeAirport();
       
        initializeFlights();
    }
    public void initializeValues(){
        flightDataLists.getAdmins().add(new Admin("a1firstName","a1lastName","admin1@example.com","admin1"));
        flightDataLists.getAdmins().add(new Admin("a2firstName","a2lastName","admin2@example.com","admin2"));
        flightDataLists.getAdmins().add(new Admin("a3firstName","a3lastName","admin3@example.com","admin3"));
        
        flightDataLists.getCustomers().add(new Customer("c1firstName","c1lastName","customer1@example.com","customer1"));
        flightDataLists.getCustomers().add(new Customer("c2firstName","c2lastName","customer2@example.com","customer2"));
        flightDataLists.getCustomers().add(new Customer("c3firstName","c3lastName","customer3@example.com","customer3"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void initializeAirport(){
        flightDataLists.getAirports().add(new Airport("Istanbul Airport","Istanbul","Turkey"));
        flightDataLists.getAirports().add(new Airport("Heathrow Airport","London","United Kingdom"));
        flightDataLists.getAirports().add(new Airport("Tokyo Haneda Airport","Tokyo","Japan"));
        flightDataLists.getAirports().add(new Airport("Singapore Changi Airport","Changi","Singapore"));
    }   
    
    public void initializeFlights(){  
        LocalDateTime dT1= LocalDateTime.now().plusDays(1).withHour(16).withMinute(30);
        LocalDateTime dT2= LocalDateTime.now().plusDays(1).withHour(9).withMinute(0); 
        
                    flightDataLists.getFlights().add(new Flight(airports.elementAt(0),airports.elementAt(1)
                            ,dT1,6,200));
                    flightDataLists.getFlights().add(new Flight(airports.elementAt(1),airports.elementAt(2)
                            ,dT2,5,100));
                    flightDataLists.getFlights().add(new Flight(airports.elementAt(0),airports.elementAt(2)
                            ,dT1,4,300));  
                    flightDataLists.getFlights().add(new Flight(airports.elementAt(2),airports.elementAt(1)
                            ,dT2,8,150));
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    public void showPanelMethod(String panelName){
        cardLayout.show(mainPanel, panelName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
