/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import FlightReservationExceptions.EmptyFieldException;
import FlightReservationExceptions.InvalidEmailFormatException;
import FlightReservationExceptions.UsedEmailException;
import OperationsAndServices.EmailValidator;
import OperationsAndServices.FlightDataLists;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import reservationObjects.Customer;

/**
 *
 * @author Zahera
 */
public class RegisterPage extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPage
     */
    MainFrame mainFrame;
    FlightDataLists flightDataLists;

    public RegisterPage(MainFrame mainFrame, FlightDataLists flightDataLists) {
        this.mainFrame = mainFrame;
        this.flightDataLists = flightDataLists;
        initComponents();
        buttonGroup1.add(radiobtn_male);
        buttonGroup1.add(radiobtn_female);
        radiobtn_male.setSelected(true);//will select male until it changed manually, benefit: no empty field exception for radioButtons
        for (int i = 1; i <= 31; i++) {
            comboDay.addItem(String.valueOf(i));
        }
        for (int i = 1; i <= 12; i++) {
            comboMonth.addItem(String.valueOf(i));
        }
        txt_birthYear.setName(" birth year ");
        txt_email.setName(" email ");
        txt_firstName.setName(" first Name ");
        txt_lastName.setName(" last Name ");
        txt_password.setName(" password ");

    }

    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_registerForm = new javax.swing.JLabel();
        showLoginPage = new javax.swing.JButton();
        lbl_FirstName = new javax.swing.JLabel();
        lbl_LastName = new javax.swing.JLabel();
        lbl_dateOfBirth = new javax.swing.JLabel();
        comboDay = new javax.swing.JComboBox<>();
        comboMonth = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbl_month = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        radiobtn_male = new javax.swing.JRadioButton();
        radiobtn_female = new javax.swing.JRadioButton();
        lbl_haveSignedBefore = new javax.swing.JLabel();
        txt_birthYear = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();

        lbl_registerForm.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lbl_registerForm.setForeground(new java.awt.Color(0, 153, 153));
        lbl_registerForm.setText("Register Form");

        showLoginPage.setBackground(new java.awt.Color(153, 255, 204));
        showLoginPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showLoginPage.setText("goToLoginPage");
        showLoginPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLoginPageActionPerformed(evt);
            }
        });

        lbl_FirstName.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_FirstName.setText("First Name");

        lbl_LastName.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_LastName.setText("Last Name");

        lbl_dateOfBirth.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_dateOfBirth.setText("Date of birth");

        jLabel3.setText("day");

        lbl_month.setText("month");

        lbl_year.setText("year");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_email.setText("Email");

        lbl_password.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lbl_password.setText("Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel2.setText("Gender");

        radiobtn_male.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiobtn_male.setText("male");

        radiobtn_female.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radiobtn_female.setText("female");

        lbl_haveSignedBefore.setText("Have signed Before?");

        btn_submit.setBackground(new java.awt.Color(255, 153, 204));
        btn_submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_registerForm)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_dateOfBirth, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_haveSignedBefore)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80)
                                .addComponent(lbl_month)
                                .addGap(61, 61, 61)
                                .addComponent(lbl_year))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(showLoginPage)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_email)
                                        .addComponent(txt_password)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(radiobtn_male)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radiobtn_female)
                                            .addGap(22, 22, 22))
                                        .addComponent(txt_lastName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_firstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_registerForm)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_month)
                            .addComponent(lbl_year))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showLoginPage)
                            .addComponent(btn_submit)
                            .addComponent(lbl_haveSignedBefore)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_FirstName)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_LastName)
                        .addGap(28, 28, 28)
                        .addComponent(lbl_dateOfBirth)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_email)
                        .addGap(36, 36, 36)
                        .addComponent(lbl_password)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(radiobtn_male)
                            .addComponent(radiobtn_female))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showLoginPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLoginPageActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanelMethod("LoginPage");
    }//GEN-LAST:event_showLoginPageActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        //check if there is an empty field 

        ArrayList<JTextField> textFieldsList = new ArrayList<>();
        textFieldsList.add(txt_firstName);
        textFieldsList.add(txt_lastName);
        textFieldsList.add(txt_birthYear);
        textFieldsList.add(txt_email);
        textFieldsList.add(txt_password);
        try {
            for (JTextField jTextField : textFieldsList) {
                if (jTextField.getText().trim().isEmpty()) {
                    throw new EmptyFieldException(jTextField.getName());
                }
            }
        } catch (EmptyFieldException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
            //Adding return; after showing an error message stops the method execution,
            //so the Customer won't be added unless all validation passes.
        }
        try {
            if (!EmailValidator.isValid(txt_email.getText())) {
                if (!txt_firstName.getText().trim().isEmpty()) {
                    throw new InvalidEmailFormatException(txt_email.getText(), txt_firstName.getText());
                } else {
                    throw new InvalidEmailFormatException(txt_email.getText());
                }

            }
        } catch (InvalidEmailFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        try {
            for (Customer customer : flightDataLists.getCustomers()) {
                if (customer.getEmail().equalsIgnoreCase(txt_email.getText())) {
                    throw new UsedEmailException(txt_email.getText());
                }
            }

        } catch (UsedEmailException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        LocalDate birthDate = LocalDate.of(2000, 2, 2);
        try {
            int intYear = Integer.parseInt(txt_birthYear.getText());
            int intMonth = Integer.parseInt(comboMonth.getSelectedItem().toString());
            int intDay = Integer.parseInt(comboDay.getSelectedItem().toString());
            birthDate = Customer.fromIntToLocalDate(intYear, intMonth, intDay);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }

        int registeredCustomerNumber = flightDataLists.getCustomers().size();
        flightDataLists.getCustomers().add(new Customer( txt_firstName.getText(),
                txt_lastName.getText(), txt_email.getText(), txt_password.getText(),birthDate));
        if (registeredCustomerNumber + 1 == flightDataLists.getCustomers().size()) {
            JOptionPane.showMessageDialog(null, "the user has registered successfully");
        } else {
            JOptionPane.showMessageDialog(null, "user does not registered, try to find a solution");
        }
    }//GEN-LAST:event_btn_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboDay;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_dateOfBirth;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_haveSignedBefore;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_registerForm;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JRadioButton radiobtn_female;
    private javax.swing.JRadioButton radiobtn_male;
    private javax.swing.JButton showLoginPage;
    private javax.swing.JTextField txt_birthYear;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
